[package]
name = "delv_leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4.0"
either = "1.8.1"

[[bench]]
name = "my_benchmark"
harness = false